version: 2.1

executors:
  python:
    docker:
      - image: circleci/python:3.7.4
        environment:
          PIPENV_VENV_IN_PROJECT: true

commands:
  install-python:
    steps:
      - run:
          name: Install Python dependencies
          command: |
            sudo python -m pip install -U pip setuptools pipenv tox tox-pipenv-install

jobs:
  test:
    executor: python
    steps:
      - checkout
      - install-python
      - run:
          name: Run static code analysis
          command: |
            tox -e lint
            tox -e isort
            tox -e mypy
      - run:
          name: Run tests
          command: tox -e tests
      - run:
          name: Create test coverage report
          command: coverage xml -o test-results/coverage/result.xml
      - store_test_results:
          path: test-results

workflows:
  version: 2
  test:
    jobs:
      - test
